const countries = [
  { country_id: 'COUNTRY-0001', country_name: ' Afganistán' },
{ country_id: 'COUNTRY-0002', country_name: ' Albania' },
{ country_id: 'COUNTRY-0003', country_name: ' Alemania' },
{ country_id: 'COUNTRY-0004', country_name: ' Andorra' },
{ country_id: 'COUNTRY-0005', country_name: ' Angola' },
{ country_id: 'COUNTRY-0006', country_name: ' Antigua y Barbuda' },
{ country_id: 'COUNTRY-0007', country_name: ' Arabia Saudita' },
{ country_id: 'COUNTRY-0008', country_name: ' Argelia' },
{ country_id: 'COUNTRY-0009', country_name: ' Argentina' },
{ country_id: 'COUNTRY-0010', country_name: ' Armenia' },
{ country_id: 'COUNTRY-0011', country_name: ' Australia' },
{ country_id: 'COUNTRY-0012', country_name: ' Austria' },
{ country_id: 'COUNTRY-0013', country_name: ' Azerbaiyán' },
{ country_id: 'COUNTRY-0014', country_name: ' Bahamas' },
{ country_id: 'COUNTRY-0015', country_name: ' Bangladés' },
{ country_id: 'COUNTRY-0016', country_name: ' Barbados' },
{ country_id: 'COUNTRY-0017', country_name: ' Baréin' },
{ country_id: 'COUNTRY-0018', country_name: ' Bélgica' },
{ country_id: 'COUNTRY-0019', country_name: ' Belice' },
{ country_id: 'COUNTRY-0020', country_name: ' Benín' },
{ country_id: 'COUNTRY-0021', country_name: ' Bielorrusia' },
{ country_id: 'COUNTRY-0022', country_name: ' Birmania' },
{ country_id: 'COUNTRY-0023', country_name: ' Bolivia' },
{ country_id: 'COUNTRY-0024', country_name: ' Bosnia y Herzegovina' },
{ country_id: 'COUNTRY-0025', country_name: ' Botsuana' },
{ country_id: 'COUNTRY-0026', country_name: ' Brasil' },
{ country_id: 'COUNTRY-0027', country_name: ' Brunéi' },
{ country_id: 'COUNTRY-0028', country_name: ' Bulgaria' },
{ country_id: 'COUNTRY-0029', country_name: ' Burkina Faso' },
{ country_id: 'COUNTRY-0030', country_name: ' Burundi' },
{ country_id: 'COUNTRY-0031', country_name: ' Bután' },
{ country_id: 'COUNTRY-0032', country_name: ' Cabo Verde' },
{ country_id: 'COUNTRY-0033', country_name: ' Camboya' },
{ country_id: 'COUNTRY-0034', country_name: ' Camerún' },
{ country_id: 'COUNTRY-0035', country_name: ' Canadá' },
{ country_id: 'COUNTRY-0036', country_name: ' Catar' },
{ country_id: 'COUNTRY-0037', country_name: ' Chad' },
{ country_id: 'COUNTRY-0038', country_name: ' Chile' },
{ country_id: 'COUNTRY-0039', country_name: ' China' },
{ country_id: 'COUNTRY-0040', country_name: ' Chipre' },
{ country_id: 'COUNTRY-0041', country_name: ' Ciudad del Vaticano' },
{ country_id: 'COUNTRY-0042', country_name: ' Colombia' },
{ country_id: 'COUNTRY-0043', country_name: ' Comoras' },
{ country_id: 'COUNTRY-0044', country_name: ' Corea del Norte' },
{ country_id: 'COUNTRY-0045', country_name: ' Corea del Sur' },
{ country_id: 'COUNTRY-0046', country_name: ' Costa de Marfil' },
{ country_id: 'COUNTRY-0047', country_name: ' Costa Rica' },
{ country_id: 'COUNTRY-0048', country_name: ' Croacia' },
{ country_id: 'COUNTRY-0049', country_name: ' Cuba' },
{ country_id: 'COUNTRY-0050', country_name: ' Dinamarca' },
{ country_id: 'COUNTRY-0051', country_name: ' Dominica' },
{ country_id: 'COUNTRY-0052', country_name: ' Ecuador' },
{ country_id: 'COUNTRY-0053', country_name: ' Egipto' },
{ country_id: 'COUNTRY-0054', country_name: ' El Salvador' },
{ country_id: 'COUNTRY-0055', country_name: ' Emiratos Árabes Unidos' },
{ country_id: 'COUNTRY-0056', country_name: ' Eritrea' },
{ country_id: 'COUNTRY-0057', country_name: ' Eslovaquia' },
{ country_id: 'COUNTRY-0058', country_name: ' Eslovenia' },
{ country_id: 'COUNTRY-0059', country_name: ' España' },
{ country_id: 'COUNTRY-0060', country_name: ' Estados Unidos' },
{ country_id: 'COUNTRY-0061', country_name: ' Estonia' },
{ country_id: 'COUNTRY-0062', country_name: ' Etiopía' },
{ country_id: 'COUNTRY-0063', country_name: ' Filipinas' },
{ country_id: 'COUNTRY-0064', country_name: ' Finlandia' },
{ country_id: 'COUNTRY-0065', country_name: ' Fiyi' },
{ country_id: 'COUNTRY-0066', country_name: ' Francia' },
{ country_id: 'COUNTRY-0067', country_name: ' Gabón' },
{ country_id: 'COUNTRY-0068', country_name: ' Gambia' },
{ country_id: 'COUNTRY-0069', country_name: ' Georgia' },
{ country_id: 'COUNTRY-0070', country_name: ' Ghana' },
{ country_id: 'COUNTRY-0071', country_name: ' Granada' },
{ country_id: 'COUNTRY-0072', country_name: ' Grecia' },
{ country_id: 'COUNTRY-0073', country_name: ' Guatemala' },
{ country_id: 'COUNTRY-0074', country_name: ' Guyana' },
{ country_id: 'COUNTRY-0075', country_name: ' Guinea' },
{ country_id: 'COUNTRY-0076', country_name: ' Guinea ecuatorial' },
{ country_id: 'COUNTRY-0077', country_name: ' Guinea-Bisáu' },
{ country_id: 'COUNTRY-0078', country_name: ' Haití' },
{ country_id: 'COUNTRY-0079', country_name: ' Honduras' },
{ country_id: 'COUNTRY-0080', country_name: ' Hungría' },
{ country_id: 'COUNTRY-0081', country_name: ' India' },
{ country_id: 'COUNTRY-0082', country_name: ' Indonesia' },
{ country_id: 'COUNTRY-0083', country_name: ' Irak' },
{ country_id: 'COUNTRY-0084', country_name: ' Irán' },
{ country_id: 'COUNTRY-0085', country_name: ' Irlanda' },
{ country_id: 'COUNTRY-0086', country_name: ' Islandia' },
{ country_id: 'COUNTRY-0087', country_name: ' Islas Marshall' },
{ country_id: 'COUNTRY-0088', country_name: ' Islas Salomón' },
{ country_id: 'COUNTRY-0089', country_name: ' Israel' },
{ country_id: 'COUNTRY-0090', country_name: ' Italia' },
{ country_id: 'COUNTRY-0091', country_name: ' Jamaica' },
{ country_id: 'COUNTRY-0092', country_name: ' Japón' },
{ country_id: 'COUNTRY-0093', country_name: ' Jordania' },
{ country_id: 'COUNTRY-0094', country_name: ' Kazajistán' },
{ country_id: 'COUNTRY-0095', country_name: ' Kenia' },
{ country_id: 'COUNTRY-0096', country_name: ' Kirguistán' },
{ country_id: 'COUNTRY-0097', country_name: ' Kiribati' },
{ country_id: 'COUNTRY-0098', country_name: ' Kuwait' },
{ country_id: 'COUNTRY-0099', country_name: ' Laos' },
{ country_id: 'COUNTRY-0100', country_name: ' Lesoto' },
{ country_id: 'COUNTRY-0101', country_name: ' Letonia' },
{ country_id: 'COUNTRY-0102', country_name: ' Líbano' },
{ country_id: 'COUNTRY-0103', country_name: ' Liberia' },
{ country_id: 'COUNTRY-0104', country_name: ' Libia' },
{ country_id: 'COUNTRY-0105', country_name: ' Liechtenstein' },
{ country_id: 'COUNTRY-0106', country_name: ' Lituania' },
{ country_id: 'COUNTRY-0107', country_name: ' Luxemburgo' },
{ country_id: 'COUNTRY-0108', country_name: ' Macedonia del Norte' },
{ country_id: 'COUNTRY-0109', country_name: ' Madagascar' },
{ country_id: 'COUNTRY-0110', country_name: ' Malasia' },
{ country_id: 'COUNTRY-0111', country_name: ' Malaui' },
{ country_id: 'COUNTRY-0112', country_name: ' Maldivas' },
{ country_id: 'COUNTRY-0113', country_name: ' Malí' },
{ country_id: 'COUNTRY-0114', country_name: ' Malta' },
{ country_id: 'COUNTRY-0115', country_name: ' Marruecos' },
{ country_id: 'COUNTRY-0116', country_name: ' Mauricio' },
{ country_id: 'COUNTRY-0117', country_name: ' Mauritania' },
{ country_id: 'COUNTRY-0118', country_name: ' México' },
{ country_id: 'COUNTRY-0119', country_name: ' Micronesia' },
{ country_id: 'COUNTRY-0120', country_name: ' Moldavia' },
{ country_id: 'COUNTRY-0121', country_name: ' Mónaco' },
{ country_id: 'COUNTRY-0122', country_name: ' Mongolia' },
{ country_id: 'COUNTRY-0123', country_name: ' Montenegro' },
{ country_id: 'COUNTRY-0124', country_name: ' Mozambique' },
{ country_id: 'COUNTRY-0125', country_name: ' Namibia' },
{ country_id: 'COUNTRY-0126', country_name: ' Nauru' },
{ country_id: 'COUNTRY-0127', country_name: ' Nepal' },
{ country_id: 'COUNTRY-0128', country_name: ' Nicaragua' },
{ country_id: 'COUNTRY-0129', country_name: ' Níger' },
{ country_id: 'COUNTRY-0130', country_name: ' Nigeria' },
{ country_id: 'COUNTRY-0131', country_name: ' Noruega' },
{ country_id: 'COUNTRY-0132', country_name: ' Nueva Zelanda' },
{ country_id: 'COUNTRY-0133', country_name: ' Omán' },
{ country_id: 'COUNTRY-0134', country_name: ' Países Bajos' },
{ country_id: 'COUNTRY-0135', country_name: ' Pakistán' },
{ country_id: 'COUNTRY-0136', country_name: ' Palaos' },
{ country_id: 'COUNTRY-0137', country_name: ' Panamá' },
{ country_id: 'COUNTRY-0138', country_name: ' Papúa Nueva Guinea' },
{ country_id: 'COUNTRY-0139', country_name: ' Paraguay' },
{ country_id: 'COUNTRY-0140', country_name: ' Perú' },
{ country_id: 'COUNTRY-0141', country_name: ' Polonia' },
{ country_id: 'COUNTRY-0142', country_name: ' Portugal' },
{ country_id: 'COUNTRY-0143', country_name: ' Reino Unido' },
{ country_id: 'COUNTRY-0144', country_name: ' República Centroafricana' },
{ country_id: 'COUNTRY-0145', country_name: ' República Checa' },
{ country_id: 'COUNTRY-0146', country_name: ' República del Congo' },
{ country_id: 'COUNTRY-0147', country_name: ' República Democrática del Congo' },
{ country_id: 'COUNTRY-0148', country_name: ' República Dominicana' },
{ country_id: 'COUNTRY-0149', country_name: ' Ruanda' },
{ country_id: 'COUNTRY-0150', country_name: ' Rumanía' },
{ country_id: 'COUNTRY-0151', country_name: ' Rusia' },
{ country_id: 'COUNTRY-0152', country_name: ' Samoa' },
{ country_id: 'COUNTRY-0153', country_name: ' San Cristóbal y Nieves' },
{ country_id: 'COUNTRY-0154', country_name: ' San Marino' },
{ country_id: 'COUNTRY-0155', country_name: ' San Vicente y las Granadinas' },
{ country_id: 'COUNTRY-0156', country_name: ' Santa Lucía' },
{ country_id: 'COUNTRY-0157', country_name: ' Santo Tomé y Príncipe' },
{ country_id: 'COUNTRY-0158', country_name: ' Senegal' },
{ country_id: 'COUNTRY-0159', country_name: ' Serbia' },
{ country_id: 'COUNTRY-0160', country_name: ' Seychelles' },
{ country_id: 'COUNTRY-0161', country_name: ' Sierra Leona' },
{ country_id: 'COUNTRY-0162', country_name: ' Singapur' },
{ country_id: 'COUNTRY-0163', country_name: ' Siria' },
{ country_id: 'COUNTRY-0164', country_name: ' Somalia' },
{ country_id: 'COUNTRY-0165', country_name: ' Sri Lanka' },
{ country_id: 'COUNTRY-0166', country_name: ' Suazilandia' },
{ country_id: 'COUNTRY-0167', country_name: ' Sudáfrica' },
{ country_id: 'COUNTRY-0168', country_name: ' Sudán' },
{ country_id: 'COUNTRY-0169', country_name: ' Sudán del Sur' },
{ country_id: 'COUNTRY-0170', country_name: ' Suecia' },
{ country_id: 'COUNTRY-0171', country_name: ' Suiza' },
{ country_id: 'COUNTRY-0172', country_name: ' Surinam' },
{ country_id: 'COUNTRY-0173', country_name: ' Tailandia' },
{ country_id: 'COUNTRY-0174', country_name: ' Tanzania' },
{ country_id: 'COUNTRY-0175', country_name: ' Tayikistán' },
{ country_id: 'COUNTRY-0176', country_name: ' Timor Oriental' },
{ country_id: 'COUNTRY-0177', country_name: ' Togo' },
{ country_id: 'COUNTRY-0178', country_name: ' Tonga' },
{ country_id: 'COUNTRY-0179', country_name: ' Trinidad y Tobago' },
{ country_id: 'COUNTRY-0180', country_name: ' Túnez' },
{ country_id: 'COUNTRY-0181', country_name: ' Turkmenistán' },
{ country_id: 'COUNTRY-0182', country_name: ' Turquía' },
{ country_id: 'COUNTRY-0183', country_name: ' Tuvalu' },
{ country_id: 'COUNTRY-0184', country_name: ' Ucrania' },
{ country_id: 'COUNTRY-0185', country_name: ' Uganda' },
{ country_id: 'COUNTRY-0186', country_name: ' Uruguay' },
{ country_id: 'COUNTRY-0187', country_name: ' Uzbekistán' },
{ country_id: 'COUNTRY-0188', country_name: ' Vanuatu' },
{ country_id: 'COUNTRY-0189', country_name: ' Venezuela' },
{ country_id: 'COUNTRY-0190', country_name: ' Vietnam' },
{ country_id: 'COUNTRY-0191', country_name: ' Yemen' },
{ country_id: 'COUNTRY-0192', country_name: ' Yibuti' },
{ country_id: 'COUNTRY-0193', country_name: ' Zambia' },
{ country_id: 'COUNTRY-0194', country_name: ' Zimbabue' }

]


module.exports = countries;
